server:
  port: 80
  address: 0.0.0.0
  servlet:
    session:
      timeout: 7D
      cookie:
        max-age: 7D
        http-only: true
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/OurNews-test
  redis:
    host: localhost
    port: 6379
    database: 0
  resources:
    cache:
      cachecontrol:
        max-age: 7D