server:
  port: 80
  address: 0.0.0.0
  servlet:
    session:
      timeout: 7D
      cookie:
        max-age: 7D
        http-only: true
  tomcat:
    uri-encoding: UTF-8
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/OurNews-test
  redis:
    host: localhost
    port: 6379
    database: 0
  resources:
    cache:
      cachecontrol:
        max-age: 7D
    static-locations: classpath:static/,file:static/
  http:
    encoding:
      charset: UTF-8
  config:
    location: classpath:application.yml,file:application.yml

data:
  db-home: static/DBData/
  net-news-data: net_news_data.txt
  img: img.txt
  theta: THETA.txt